In [10]:
import pandas as pd
import numpy as np
from tqdm import tqdm

In [11]:
train = pd.read_csv("battles_updated.csv")
test = pd.read_csv("tests.csv")
pokemon = pd.read_csv("pokemon.csv")
typechart = pd.read_csv("chart.csv")

In [12]:
train

,second_Type 1,second_Type 2,second_HP,second_Attack,second_Defense,second_Sp. Atk,second_Sp. Def,second_Speed,first_Type 1,first_Type 2,first_HP,first_Attack,first_Defense,first_Sp. Atk,first_Sp. Def,first_Speed,First_pokemon,Second_pokemon,outcome
0,Grass,Poison,45,24,49,32,65,45,Normal,Flying,40,90,40,70,35,56,21,1,0
1,Grass,Poison,45,49,49,65,65,45,Normal,No Type,30,56,35,25,35,72,25,1,0
2,Grass,Poison,45,12,49,16,65,45,Grass,Poison,60,16,70,21,75,40,50,1,1
3,Grass,Poison,45,24,49,32,65,45,Fire,No Type,55,140,45,140,50,60,64,1,0
4,Grass,Poison,45,12,49,16,65,45,Grass,Poison,50,18,35,17,30,40,76,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,Fire,Water,80,220,120,260,90,70,Bug,Flying,80,26,50,45,50,89,735,800,0
49996,Fire,Water,80,27,120,32,90,70,Poison,Water,50,60,60,60,60,30,761,800,1
49997,Fire,Water,80,27,120,32,90,70,Poison,Water,50,60,60,60,60,30,761,800,1
49998,Fire,Water,80,27,120,32,90,70,Dragon,No Type,68,75,53,83,113,60,776,800,1
49999,Fire,Water,80,110,120,130,90,70,Ghost,Grass,59,66,70,44,55,41,784,800,1